export const attributeConfig = {
  attributeTitle: "Select Attribute",
  attributeItems: [
    {
      name: "v-model",
      desc: "当前选中的项",
      type: "String",
      value: "_",
      defaultValue: "_",
    },
    {
      name: "placeHolder",
      desc: "未选中时的提示",
      type: "String",
      value: "_",
      defaultValue: "请选择",
    },
    {
      name: "data",
      desc: "数据源",
      type: "Array",
      value: "_",
      defaultValue: "required",
    },
    {
      name: "width",
      desc: "select宽度",
      type: "Number/String",
      value: "_",
      defaultValue: "_",
    },
    {
      name: "searchSelect",
      desc: "是否搜索",
      type: "Boolean",
      value: "_",
      defaultValue: "false",
    },
    {
      name: "clearable",
      desc: "可清除",
      type: "Boolean",
      value: "_",
      defaultValue: "false",
    },
    {
      name: "disabled",
      desc: "select禁用",
      type: "Boolean",
      value: "_",
      defaultValue: "false",
    }, {
      name: "searchFilterDisabled",
      desc: "搜索过滤禁选项",
      type: "Boolean",
      value: "_",
      defaultValue: "false",
    },
  ],
};
